### PR TITLE
add category repository

### PR DESCRIPTION
**Pull request by duongricky**

### CODE REVIEW

**Comment by duongricky** [comment]
ready

**Comment by duongricky** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
3 commit rồi em. gộp lại đi

**Comment by duongricky** [comment]
ready

**Comment by duongricky** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
conflict

**Comment by duongricky** [comment]
ready

**Pull request merged**
